### ISSUE TITLE
name->color does not use normalize-color-string

### ISSUE THREAD

**Issue by maueroats** [racket/picturing-programs#4]
Issue with Racket 8.0.0.3 (cs), picturing-programs pulled from github.
```
(name->color "grey") 
;; #false
```
Expected response: `(make-color 190 190 190 255)`, the same as created by `(name->color "gray")`.

Source of problem: the function directly uses `the-color-database` rather than going through some interface function from 2htdp.

See PR #3

**Comment by mfelleisen** [comment]
Would this prevent you from using 8.0?

**Comment by maueroats** [comment]
No. I think this is a long-standing bug.
