### ISSUE TITLE
cannot colorize transparent

### ISSUE THREAD

**Issue by maueroats** [racket/picturing-programs#9]
The `color%->color` function explicitly does not copy the alpha channel, so `(colorize "transparent")` produces white, the same result as `(colorize "white")`.

I am a bit concerned about patching this because the original code explicitly mentions making the alpha channel 255, but I'm not sure why.

I believe the original intent was to use `#false` for transparent.

```scheme
(colorize "transparent")
(make-color 255 255 255 255)
```

**Comment by rfindler** [comment]
> Ouch: "Note that color% doesn't have an alpha component, so alpha is lost."

I think that was true in the past, but it isn't anymore. Here are the docs: https://docs.racket-lang.org/draw/color_.html . It may be possible to do something about this.

**Comment by soegaard** [comment]
That comment applies to `color->color%`which discards the alpha channel.

https://github.com/racket/picturing-programs/blob/f2ce24d8e7cbefe585e3d849324b61ad2e680556/picturing-programs/private/map-image.rkt#L88

**Comment by maueroats** [comment]
See PR #10
